Repository ZB-ChalKak/chalKak-back, pull requests merged in 2023-08, with the labels that each got.

#33 [#31] comment 조회/생성/삭제/수정 기능
  src/main/java/com/btb/chalKak/domain/comment/controller/CommentController.java
  src/main/java/com/btb/chalKak/domain/comment/dto/request/CreateCommentRequest.java
  src/main/java/com/btb/chalKak/domain/comment/dto/request/DeleteCommentRequest.java
  src/main/java/com/btb/chalKak/domain/comment/dto/request/ModifyCommentRequest.java
  src/main/java/com/btb/chalKak/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/btb/chalKak/domain/comment/entity/Comment.java
  src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java
  src/main/java/com/btb/chalKak/domain/comment/service/CommentService.java
  src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
Labels: feature

#36 게시판 기능 개발
  src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostController.java
  src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java
  src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostsResponse.java
  src/main/java/com/btb/chalKak/domain/post/entity/Post.java
  src/main/java/com/btb/chalKak/domain/post/repository/CustomPostRepository.java
  src/main/java/com/btb/chalKak/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/btb/chalKak/scheduler/PostScheduler.java
  src/main/resources/application.yml
  src/test/java/com/btb/chalKak/domain/post/service/impl/PostServiceImplTest.java
Labels: feature

#38 [#31] feat : comment 조회/생성/수정 Test 완료
  src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java
  src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java
Labels: fix

#39 [#12] feat : openWeather로 날씨 정보 api 구현
  build.gradle
  src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java
  src/main/java/com/btb/chalKak/domain/weather/controller/WeatherController.java
  src/main/java/com/btb/chalKak/domain/weather/dto/WeatherDto.java
  src/main/java/com/btb/chalKak/domain/weather/service/WeatherService.java
  src/main/resources/application-oauth.yml
Labels: feature

#40 회원가입, 로그인, 토큰 구현
  src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java
  src/main/java/com/btb/chalKak/common/security/JwtAuthenticationFilter.java
  src/main/java/com/btb/chalKak/common/security/JwtProvider.java
  src/main/java/com/btb/chalKak/common/security/dto/TokenDto.java
  src/main/java/com/btb/chalKak/common/security/entity/RefreshToken.java
  src/main/java/com/btb/chalKak/common/security/provider/CustomAuthenticationProvider.java
  src/main/java/com/btb/chalKak/common/security/repository/RefreshTokenRepository.java
  src/main/java/com/btb/chalKak/common/security/request/TokenRequestDto.java
  src/main/java/com/btb/chalKak/common/security/service/Impl/CustomUserDetailsService.java
  src/main/java/com/btb/chalKak/domain/member/controller/SignController.java
  src/main/java/com/btb/chalKak/domain/member/dto/request/SignInMemberRequest.java
  src/main/java/com/btb/chalKak/domain/member/dto/request/SignUpMemberRequest.java
  src/main/java/com/btb/chalKak/domain/member/dto/response/SignInMemberResponse.java
  src/main/java/com/btb/chalKak/domain/member/entity/Member.java
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
  src/main/java/com/btb/chalKak/domain/styleTag/repository/StyleTagRepository.java
  src/main/resources/application.yml
  src/test/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImplTest.java
Labels: feature

#42 회원가입 및 로그인 기능 수정 #41
  src/main/java/com/btb/chalKak/common/exception/GlobalExceptionHandler.java
  src/main/java/com/btb/chalKak/common/exception/MemberException.java
  src/main/java/com/btb/chalKak/common/response/type/ErrorCode.java
  src/main/java/com/btb/chalKak/domain/member/dto/request/SignUpMemberRequest.java
  src/main/java/com/btb/chalKak/domain/member/repository/MemberRepository.java
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
Labels: fix

#50 [#48] feat : follow 기능 구현
  src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java
  src/main/java/com/btb/chalKak/domain/follow/controller/FollowController.java
  src/main/java/com/btb/chalKak/domain/follow/entity/Follow.java
  src/main/java/com/btb/chalKak/domain/follow/repository/FollowRepository.java
  src/main/java/com/btb/chalKak/domain/follow/service/FollowService.java
  src/main/java/com/btb/chalKak/domain/like/entity/Like.java
  src/test/java/com/btb/chalKak/domain/follow/service/FollowServiceTest.java
Labels: feature

#51 [#41] feat : member provider 추가
  src/main/java/com/btb/chalKak/domain/follow/entity/Follow.java
  src/main/java/com/btb/chalKak/domain/member/entity/Member.java
  src/main/java/com/btb/chalKak/domain/member/type/MemberProvider.java
  src/main/resources/table/h2/data.sql
  src/main/resources/table/h2/schema.sql
Labels: fix, feature

#52 [#41] feat : member provider 검증 추가
  src/main/java/com/btb/chalKak/common/oauth2/dto/OAuthAttributes.java
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/resources/table/h2/schema.sql
  src/main/resources/table/mySql/data.sql
  src/main/resources/table/mySql/schema.sql
Labels: fix, feature

#53 회원가입 로직 수정
  src/main/java/com/btb/chalKak/common/exception/MemberException.java
  src/main/java/com/btb/chalKak/common/response/type/ErrorCode.java
  src/main/java/com/btb/chalKak/common/response/type/SuccessCode.java
  src/main/java/com/btb/chalKak/common/security/JwtAuthenticationFilter.java
  src/main/java/com/btb/chalKak/common/security/JwtProvider.java
  src/main/java/com/btb/chalKak/common/security/customUser/CustomUserDetails.java
  src/main/java/com/btb/chalKak/common/security/customUser/CustomUserDetailsService.java
  src/main/java/com/btb/chalKak/common/security/provider/CustomAuthenticationProvider.java
  src/main/java/com/btb/chalKak/common/util/ValidationUtils.java
  src/main/java/com/btb/chalKak/config/SecurityConfig.java
  src/main/java/com/btb/chalKak/domain/member/controller/SignController.java
  src/main/java/com/btb/chalKak/domain/member/dto/Writer.java
  src/main/java/com/btb/chalKak/domain/member/dto/request/SignUpMemberRequest.java
  src/main/java/com/btb/chalKak/domain/member/entity/Member.java
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
  src/main/java/com/btb/chalKak/domain/member/type/MemberStatus.java
  src/main/resources/application.yml
Labels: fix

#55 [#43] feat : OAuth2SuccessHandler 수정
  src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
Labels: feature

#56 게시판 기능 개발 (수정)
  src/main/java/com/btb/chalKak/common/exception/PostException.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostController.java
  src/main/java/com/btb/chalKak/domain/post/dto/request/WritePostRequest.java
  src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java
  src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostsResponse.java
  src/main/java/com/btb/chalKak/domain/post/dto/response/WritePostResponse.java
  src/main/java/com/btb/chalKak/domain/post/entity/Post.java
  src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/btb/chalKak/domain/styleTag/entity/StyleTag.java
  src/main/java/com/btb/chalKak/scheduler/PostScheduler.java
  src/main/resources/table/h2/data.sql
  src/main/resources/table/h2/schema.sql
  src/main/resources/table/mySql/data.sql
  src/main/resources/table/mySql/schema.sql
  src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java
  src/test/java/com/btb/chalKak/domain/post/service/impl/PostServiceImplTest.java
Labels: fix, feature

#66 [#60] feat : swagger2 설정
  build.gradle
  src/main/java/com/btb/chalKak/config/SwaggerConfig.java
Labels: feature

#75 Feature/#31 comment fix
  .travis.yml
  src/main/java/com/btb/chalKak/domain/comment/dto/response/CommentLoadResponse.java
  src/main/java/com/btb/chalKak/domain/comment/service/CommentService.java
  src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
  src/main/resources/table/h2/data.sql
  src/main/resources/table/h2/schema.sql
  src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java
Labels: fix

#85 Feature/#80 like dto
  src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java
  src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/btb/chalKak/domain/like/controller/LikeController.java
  src/main/java/com/btb/chalKak/domain/like/dto/LikeResponse.java
  src/main/java/com/btb/chalKak/domain/like/service/LikeService.java
  src/main/resources/table/h2/data.sql
Labels: fix

#90 [#89] fix : 충돌 해결을 위한 커밋
  src/main/java/com/btb/chalKak/domain/post/dto/response/LoadPublicPostDetailsResponse.java
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Labels: fix

#95 test : 테스트를 위한 조회수 증가 로직 제거
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#99 Feature/#94 follow fix
  .gitignore
  build.gradle
  src/main/java/com/btb/chalKak/domain/follow/controller/FollowController.java
  src/main/java/com/btb/chalKak/domain/follow/service/FollowService.java
  src/main/java/com/btb/chalKak/domain/photo/controller/PhotoController.java
  src/main/java/com/btb/chalKak/domain/photo/entity/Photo.java
  src/main/java/com/btb/chalKak/domain/photo/repository/PhotoRepository.java
  src/main/java/com/btb/chalKak/domain/photo/service/PhotoService.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostController.java
  src/main/java/com/btb/chalKak/domain/post/dto/request/WritePostRequest.java
  src/main/java/com/btb/chalKak/domain/post/entity/Post.java
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/application-google.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: feature

#100 [#96] fix : conflict fix
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Labels: fix
