Repository ZB-ChalKak/chalKak-back, pull requests merged in 2023-09, with the labels that each got.

#101 [#96] fix : oauth2
  src/main/java/com/btb/chalKak/config/SecurityConfig.java
Labels: fix

#102 [#60] chore : oauth2 redirect-uri
  src/main/resources/application-oauth.yml
Labels: fix

#103 [#60] fix : oauth2 refresh 중복 체크, tokenservice 삭제
  src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java
  src/main/java/com/btb/chalKak/common/oauth2/controller/oauth2TokenController.java
  src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/btb/chalKak/common/oauth2/service/TemporaryTokenStoreService.java
  src/main/java/com/btb/chalKak/common/security/service/Impl/TokenServiceImpl.java
  src/main/java/com/btb/chalKak/common/security/service/TokenService.java
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
Labels: feature

#105 [#104] fix : comment pageable 기능 추가
  src/main/java/com/btb/chalKak/domain/comment/controller/CommentController.java
  src/main/java/com/btb/chalKak/domain/comment/dto/response/LoadPageCommentsResponse.java
  src/main/java/com/btb/chalKak/domain/comment/repository/CommentRepository.java
  src/main/java/com/btb/chalKak/domain/comment/service/CommentService.java
  src/main/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/btb/chalKak/domain/comment/service/impl/CommentServiceImplTest.java
Labels: feature

#117 [#31] fix : CommentLoadResponse memberId 추가
  src/main/java/com/btb/chalKak/domain/comment/dto/response/CommentLoadResponse.java
  src/main/java/com/btb/chalKak/domain/comment/dto/response/LoadPageCommentsResponse.java
Labels: fix

#120 [#104] feat : cookie 추가
  src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
  src/main/resources/application-oauth.yml
Labels: feature

#123 키워드를 통한 추천 서비스 작성
  src/main/java/com/btb/chalKak/domain/follow/controller/FollowController.java
  src/main/java/com/btb/chalKak/domain/follow/entity/Follow.java
  src/main/java/com/btb/chalKak/domain/follow/service/FollowService.java
  src/main/java/com/btb/chalKak/domain/like/entity/Like.java
  src/main/java/com/btb/chalKak/domain/member/entity/Member.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostController.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostFilterController.java
  src/main/java/com/btb/chalKak/domain/post/dto/request/LoadPublicFeaturedPostsRequest.java
  src/main/java/com/btb/chalKak/domain/post/entity/Post.java
  src/main/java/com/btb/chalKak/domain/post/repository/CustomPostRepository.java
  src/main/java/com/btb/chalKak/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#154 [#12] fix : success handler redirect 수정
  src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/btb/chalKak/common/oauth2/service/CustomOAuth2UserService.java
Labels: fix

#159 Feat/#158 load following posts
  src/main/java/com/btb/chalKak/common/exception/type/SuccessCode.java
  src/main/java/com/btb/chalKak/domain/follow/repository/CustomFollowRepository.java
  src/main/java/com/btb/chalKak/domain/follow/repository/FollowRepository.java
  src/main/java/com/btb/chalKak/domain/follow/repository/impl/CustomFollowRepositoryImpl.java
  src/main/java/com/btb/chalKak/domain/follow/service/FollowService.java
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostFilterController.java
  src/main/java/com/btb/chalKak/domain/post/repository/CustomPostRepository.java
  src/main/java/com/btb/chalKak/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/main/java/com/btb/chalKak/domain/post/service/PostService.java
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#163 [#162] fix : 게시글 수정시 이미지 삭제되지 않는 기능 수정
  src/main/java/com/btb/chalKak/domain/post/service/impl/PostServiceImpl.java
Labels: fix

#164 [#148] follower, following count가 서로 뒤바뀌어 있는 문제 수정 + refactor
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/btb/chalKak/domain/member/service/MemberService.java
Labels: fix, refactor

#171 리팩토링(좋아요, 게시글 수정)
  src/main/java/com/btb/chalKak/domain/like/service/LikeService.java
  src/main/java/com/btb/chalKak/domain/post/controller/PostController.java
Labels: refactor

#177 [#175] feat : like 추가시 post count++
  src/main/java/com/btb/chalKak/domain/like/service/LikeService.java
  src/main/java/com/btb/chalKak/domain/post/entity/Post.java
Labels: fix

#179 [#45] fix : weather post aws test
  src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
Labels: fix

#181 [#45] fix : weather Exception add
  src/main/java/com/btb/chalKak/common/exception/type/ErrorCode.java
  src/main/java/com/btb/chalKak/domain/weather/repository/WeatherRepository.java
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
Labels: fix

#183 [#45] fix : today string log 추가, repository geo 수정
  src/main/java/com/btb/chalKak/domain/weather/repository/WeatherRepository.java
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
Labels: fix

#184 [#45] fix : date-format-to-string
  src/main/java/com/btb/chalKak/domain/weather/repository/WeatherRepository.java
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
Labels: fix

#186 [#12] feat : RecommendPostBatchService 구현
  src/main/java/com/btb/chalKak/domain/batchpost/service/RecommendPostBatchService.java
  src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
  src/test/java/com/btb/chalKak/domain/batchpost/service/RecommendPostBatchServiceTest.java
Labels: feature

#195 Feature/#194 smtp
  src/main/java/com/btb/chalKak/domain/member/dto/request/ConfirmAuthRequest.java
Labels: feature

#205 [#12] feat : batch 구조 완성, 첫번째 청크에서 지연로딩이 발생하지 않지만
  src/main/java/com/btb/chalKak/batch/BatchConfiguration.java
  src/main/java/com/btb/chalKak/batch/listener/TableClearingListener.java
  src/main/java/com/btb/chalKak/batch/processor/PostItemProcessor.java
  src/main/java/com/btb/chalKak/batch/reader/PostItemReader.java
  src/main/java/com/btb/chalKak/batch/writer/RecommendPostItemWriter.java
  src/main/java/com/btb/chalKak/common/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/btb/chalKak/domain/batchpost/dto/RecommendPostBatchDTO.java
  src/main/java/com/btb/chalKak/domain/batchpost/entity/RecommendPostBatch.java
  src/main/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepository.java
  src/main/java/com/btb/chalKak/domain/post/dto/PostRecommendDto.java
  src/main/java/com/btb/chalKak/domain/post/entity/Post.java
  src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java
Labels: feature

#207 Fix/#206 userinfo
  src/main/java/com/btb/chalKak/domain/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/btb/chalKak/domain/post/repository/PostRepository.java
Labels: fix

#211 [#12] fix : weather post 정렬
  src/main/java/com/btb/chalKak/domain/batchpost/repository/RecommendPostBatchRepository.java
Labels: fix

#213 [#12] fix : 스케쥴러 bug 수정
  src/main/java/com/btb/chalKak/scheduler/WeatherScheduler.java
Labels: fix

#214 Feature/#12 weather api db connect
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
Labels: fix

#215 #12 chore : 기본 코드 삭제
  src/main/java/com/btb/chalKak/domain/weather/service/Impl/WeatherServiceImpl.java
Labels: fix

#219 Feature/follow variable modify
  src/main/java/com/btb/chalKak/domain/follow/controller/FollowController.java
  src/main/java/com/btb/chalKak/domain/follow/dto/response/LoadPageFollowerResponse.java
  src/main/java/com/btb/chalKak/domain/follow/dto/response/LoadPageFollowingResponse.java
  src/main/java/com/btb/chalKak/domain/follow/service/FollowService.java
  src/main/java/com/btb/chalKak/domain/like/controller/LikeController.java
Labels: fix
